apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wealthfolio-env
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: wealthfolio-env
    creationPolicy: Owner
  data:
    - secretKey: WF_SECRET_KEY
      remoteRef:
        key: /homelab/apps/wealthfolio/WF_SECRET_KEY
    - secretKey: WF_AUTH_PASSWORD_HASH
      remoteRef:
        key: /homelab/apps/wealthfolio/WF_AUTH_PASSWORD_HASH
