apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-mongo-env
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: unifi-mongo-env
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: /homelab/apps/unifi/MONGO_INITDB_ROOT_PASSWORD
    - secretKey: MONGO_PASS
      remoteRef:
        key: /homelab/apps/unifi/MONGO_PASS
