apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-mongo
  namespace: infra
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi-mongo
  template:
    metadata:
      labels:
        app: unifi-mongo
    spec:
      nodeSelector:
        kubernetes.io/hostname: jitte
      containers:
        - name: mongodb
          image: mongo:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unifi-mongo-env
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_USER
              value: unifi
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: unifi-mongo-env
                  key: MONGO_PASS
            - name: MONGO_DBNAME
              value: unifi
            - name: MONGO_AUTHSOURCE
              value: admin
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: init
              mountPath: /docker-entrypoint-initdb.d/init-mongo.sh
              subPath: init-mongo.sh
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: unifi-mongo-data
        - name: init
          configMap:
            name: unifi-mongo-init
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-mongo
  namespace: infra
spec:
  selector:
    app: unifi-mongo
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
