apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: infra
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: external-dns-cloudflare
    creationPolicy: Owner
  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: /homelab/cloudflare/externaldns/token
    - secretKey: CF_TUNNEL_ID
      remoteRef:
        key: /homelab/cloudflare/tunnel/homelab/id