apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-dashboard-auth
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: hermes-dashboard-auth
    creationPolicy: Owner
  data:
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
      remoteRef:
        key: /homelab/apps/hermes/HERMES_DASHBOARD_BASIC_AUTH_PASSWORD
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_SECRET
      remoteRef:
        key: /homelab/apps/hermes/HERMES_DASHBOARD_BASIC_AUTH_SECRET
