apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bifrost
  namespace: aiops
spec:
  ingressClassName: traefik
  rules:
    - host: bifrost.stoneforge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bifrost
                port:
                  number: 8080
