apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure-env
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: sure-env
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /homelab/apps/sure/POSTGRES_PASSWORD
    - secretKey: SECRET_KEY_BASE
      remoteRef:
        key: /homelab/apps/sure/SECRET_KEY_BASE
