apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      nodeSelector:
        kubernetes.io/hostname: jitte
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: adguard
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 3001
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: conf
              mountPath: /opt/adguardhome/conf
            - name: work
              mountPath: /opt/adguardhome/work
      volumes:
        - name: conf
          persistentVolumeClaim:
            claimName: adguard-conf
        - name: work
          persistentVolumeClaim:
            claimName: adguard-work