apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oidc-proxy
  namespace: infra
spec:
  ingressClassName: traefik
  rules:
    - host: oidc.stoneforge.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oidc-proxy
                port:
                  number: 80
