apiVersion: v1
kind: ServiceAccount
metadata:
  name: gtarraga-com-rollout
  namespace: projects
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gtarraga-com-rollout
  namespace: projects
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gtarraga-com-rollout
  namespace: projects
subjects:
  - kind: ServiceAccount
    name: gtarraga-com-rollout
    namespace: projects
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gtarraga-com-rollout
