apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: tailscale-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: /homelab/tailscale/oauth/client_id
    - secretKey: client_secret
      remoteRef:
        key: /homelab/tailscale/oauth/client_secret