apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papers-reading-club-env
  namespace: projects
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: papers-reading-club-env
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: /homelab/apps/papers-reading-club/ADMIN_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: /homelab/apps/papers-reading-club/DATABASE_URL
    - secretKey: NEXT_PUBLIC_POSTHOG_KEY
      remoteRef:
        key: /homelab/apps/papers-reading-club/NEXT_PUBLIC_POSTHOG_KEY
    - secretKey: NEXT_PUBLIC_POSTHOG_HOST
      remoteRef:
        key: /homelab/apps/papers-reading-club/NEXT_PUBLIC_POSTHOG_HOST
    - secretKey: TOKEN_PATTERN
      remoteRef:
        key: /homelab/apps/papers-reading-club/TOKEN_PATTERN
    - secretKey: INITIAL_TOKEN
      remoteRef:
        key: /homelab/apps/papers-reading-club/INITIAL_TOKEN
    - secretKey: INITIAL_FIRST_NAME
      remoteRef:
        key: /homelab/apps/papers-reading-club/INITIAL_FIRST_NAME
    - secretKey: INITIAL_LAST_NAME
      remoteRef:
        key: /homelab/apps/papers-reading-club/INITIAL_LAST_NAME
