apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - controllers/external-secrets
  - controllers/external-dns
  - networking/oidc-proxy
  - networking/cloudflared
