apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghostfolio
  template:
    metadata:
      labels:
        app: ghostfolio
    spec:
      containers:
        - name: ghostfolio
          image: ghostfolio/ghostfolio:3.4.0
          ports:
            - containerPort: 3333
          env:
            - name: REDIS_HOST
              value: ghostfolio-redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-env
                  key: REDIS_PASSWORD
            - name: ACCESS_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-env
                  key: ACCESS_TOKEN_SALT
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-env
                  key: JWT_SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-env
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
