apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghostfolio-env
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: ghostfolio-env
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /homelab/apps/ghostfolio/POSTGRES_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /homelab/apps/ghostfolio/REDIS_PASSWORD
    - secretKey: ACCESS_TOKEN_SALT
      remoteRef:
        key: /homelab/apps/ghostfolio/ACCESS_TOKEN_SALT
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: /homelab/apps/ghostfolio/JWT_SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: /homelab/apps/ghostfolio/DATABASE_URL
