apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: adguard-config
    files:
      - AdGuardHome.yaml=adguard-config.yaml # Adguard expects the config file to be named AdGuardHome.yaml
