apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - tailscale-service.yaml
  - adguard-config.sops.yaml
