apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandoor
  template:
    metadata:
      labels:
        app: tandoor
    spec:
      containers:
        - name: tandoor
          image: vabene1111/recipes:latest
          ports:
            - containerPort: 80
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor-secrets
                  key: SECRET_KEY
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: tandoor-postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: djangodb
            - name: POSTGRES_USER
              value: djangodb
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-secrets
                  key: POSTGRES_PASSWORD
            - name: TANDOOR_PORT
              value: "80"
            - name: ALLOWED_HOSTS
              value: tandoor.stoneforge.dev
            - name: CSRF_TRUSTED_ORIGINS
              value: https://tandoor.stoneforge.dev
            - name: ENABLE_SIGNUP
              value: "0"
            - name: TZ
              value: America/New_York
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - name: staticfiles
              mountPath: /opt/recipes/staticfiles
            - name: mediafiles
              mountPath: /opt/recipes/mediafiles
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: tandoor-staticfiles
        - name: mediafiles
          persistentVolumeClaim:
            claimName: tandoor-mediafiles
