apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-secrets
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: tandoor-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: /homelab/apps/tandoor/SECRET_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /homelab/apps/tandoor/POSTGRES_PASSWORD
